services:
  redis:
    image:
      redis:alpine
    ports:
      - 6379:6379
    networks:
      - mynet
    volumes:
      - /home/ubuntu/DEVOPS/flask-redis/data:/data
  flask:
    build:
      context: .
    ports:
      - 8000:8000
    depends_on:
      - redis
    networks:
      - mynet
networks:
  mynet:
     driver: bridge
